export const SET_USER_AUTHENTICATION_TRUE = 'SET_USER_AUTHENTICATION_TRUE';
export const SET_USER_AUTHENTICATION_FALSE = 'SET_USER_AUTHENTICATION_FALSE';
export const SET_USER_AUTHENTICATION_TOKEN = 'SET_USER_AUTHENTICATION_TOKEN';
